CREATE DATABASE BD_GESTOR_EMPLEADOS;
USE BD_GESTOR_EMPLEADOS;
CREATE TABLE EMPLEADOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    PUESTO VARCHAR(50),
    SALARIO DOUBLE,
    FECHA DATE
);

-- DROP DATABASE BD_GESTOR_EMPLEADOS --